apiVersion: batch/v1
kind: Job
metadata:
  name: Job
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels: 
        app: Job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: pi 
        image: figent/Job
